[package]
name = "homeboy"
version = "0.1.0"
edition = "2021"

[dependencies]
cortex-lang = "0.1.3-alpha"
dotenv = "0.15.0"
pest = "2.7.15"
pest_derive = "2.7.15"
regex = "1.11.1"
thiserror = "2.0.11"
