COMMENT = _{ "#" ~ (!"\n" ~ ANY)* }
WHITESPACE = _{ " " | "\n" | "\t" | "\r" }

topTemplate = { SOI ~ template ~ EOI}
template = { clause ~ ("|" ~ clause)* }
clause = { symbol* }
symbol = { (text | subtemplateCall | varBind | "(" ~ template ~ ")") ~ "?"? }

subtemplateCall = { "{" ~ subtemplateIdent ~ "}" }
varBind = { "[" ~ ident ~ "]" }
text = { ('a'..'z' | 'A'..'Z')+ }

subtemplateIdent = { (ASCII_ALPHANUMERIC | " ")+ }
ident = { ASCII_ALPHANUMERIC+ }
