COMMENT = _{ "#" ~ (!"\n" ~ ANY)* }
WHITESPACE = _{ " " | "\n" | "\t" | "\r" }

template = { SOI ~ clause ~ ("|" ~ clause)* ~ EOI }
clause = { symbol* }
symbol = { (word | subtemplateCall | varBind | "(" ~ template ~ ")") ~ "?"? }

subtemplateCall = { "{" ~ subtemplateIdent ~ "}" }
varBind = { "[" ~ ident ~ "]" }
word = { ASCII_ALPHANUMERIC+ }

subtemplateIdent = { (ASCII_ALPHANUMERIC | " ")+ }
ident = { ASCII_ALPHANUMERIC+ }
